### ISSUE TITLE
Adding scope shows as error

### ISSUE THREAD

**Issue by willasm** [joyceerhl/vscode-git-fit-commit#3]
docs(readme): message - This shows as an error.
The linting does not account for the scope.

Thanks, William.

**Comment by joyceerhl** [comment]
Thanks for reporting! Fixed with https://github.com/joyceerhl/vscode-git-fit-commit/commit/faa8b126e929071dbfc75d45fe757f3fd95dc1c9 in v1.1.1 (publishing now)
